# Generated by Django 5.2.7 on 2025-10-21 11:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('designation', '0001_initial'),
        ('works', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('joiningDate', models.DateField(blank=True, null=True)),
                ('probationPeriod', models.DateField(blank=True, null=True)),
                ('slackUsername', models.CharField(blank=True, max_length=100, null=True)),
                ('exitDate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('hourlyRate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('logIn', models.CharField(blank=True, choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Enable', max_length=20, null=True)),
                ('emailNotifications', models.CharField(blank=True, choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Enable', max_length=20, null=True)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('reportTo', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='designation.designation')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_projects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='works.work')),
            ],
        ),
    ]
