# Generated by Django 5.2.7 on 2025-10-21 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('clients', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workName', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('due', 'Due'), ('overdue', 'Overdue')], default='ongoing', max_length=20, null=True)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee')], default='USD', max_length=10, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('noDeadline', models.BooleanField(blank=True, default=False, null=True)),
                ('amc', models.BooleanField(blank=True, default=False, null=True)),
                ('amc_start_date', models.DateField(blank=True, null=True)),
                ('amc_end_date', models.DateField(blank=True, null=True)),
                ('renewable', models.BooleanField(blank=True, default=False, null=True)),
                ('renewalFrequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('halfyearly', 'Half-Yearly'), ('yearly', 'Yearly')], max_length=20, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('milestones', models.JSONField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='work_files/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.projectcategory')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
                ('workMembers', models.ManyToManyField(blank=True, null=True, related_name='works', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
